### ISSUE TITLE
Error 429 still exists

### ISSUE THREAD

**Issue by sherifkozman** [google/exposure-notifications-verification-server#303] opened 2020-08-21 14:18 UTC
We are running off commit : 691f9f5b52a538b0abbf1fb3d9c7c1fecb8809a6 while the rate limiting error 429 still persists.

[Edit by @sethvargo - removed a screenshot that contained identifiable information]

**Comment by sethvargo** [comment] 2020-08-25 01:57
Just an update on this since @sherifkozman and I are chatting offline. We believe the issue is related to scale up/down events not properly closing connections and then, eventually, exhausting the pool. We're going to investigate some service-level changes and will report back.

**Comment by mikehelmick** [comment] 2020-08-27 04:48
#391 should fix this issue.

/close

**Closed by mikehelmick** 2020-08-27 04:48 UTC
Labels: kind/bug
