### ISSUE TITLE
pha stats: expired claim attempt

### ISSUE THREAD

**Issue by mikehelmick** [google/exposure-notifications-verification-server#1232] opened 2020-12-02 00:55 UTC
### TL;DR

Number of times that expired (not invalid) codes were attempted to be claimed.

ideally an indicator of someone who go a real code but tried to use it too late.

**Comment by sethvargo** [comment] 2020-12-02 01:28
I see two use cases here:

1. You issued a code to one person and that one person did not claim it in time.

    I think this use case isn't solved by stats. The stats won't tell you _which_ user expired, and we intentionally don't have that data link.

2. You issued a bunch of codes that expired before they were claimed.

    While this data might be useful, it's not actionable. You can't re-issue the codes because there's no link back to the patient (by design).

**Comment by sethvargo** [comment] 2020-12-30 19:56
Duplicate of https://github.com/google/exposure-notifications-verification-server/issues/1497

**Comment by sethvargo** [comment] 2021-01-04 14:28
The backend piece of this is done. We opted to go for "failed" instead of "expired" which encompasses:

- codes that were definitely expired
- codes that don't exist in the database (could be super-expired or a typo)

**Closed** 2021-01-20 21:09 UTC
Labels: kind/enhancement
