### ISSUE TITLE
Is it possible to set a different JWT claim per Realm ?

### ISSUE THREAD

**Issue by sherifkozman** [google/exposure-notifications-verification-server#231] opened 2020-08-13 22:53 UTC
JWT Claim information were previously a set of ENV values across the entire service, is it possible to set a different claim per each REALM ?
@sethvargo

**Comment by mikehelmick** [comment] 2020-08-13 23:26
This is a duplicate of #149 

/close

**Closed by mikehelmick** 2020-08-13 23:26 UTC
Labels: kind/question
